@url=http://localhost:5000/api 
@json=Content-Type: application/json

###
POST  {{url}}/register
{{json}}

{
    "email":"1562288394@qqs.com",
    "nickName":"咖咖ka",
    "password":"1234563"
}

###
get {{url}}/users
{{json}}

###
post {{url}}/login
{{json}}

{
    "email":"1562288394@qqa.com",
    "password":"1234563"
}

###
post {{url}}/createArticle
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlMTQyZjdkMTFiODAzMjA2NDM3OWU0NSIsImlhdCI6MTU3ODM4MTE5MX0.J85NuPlEqHK9dJ2UwgbjN4Me7ZjJP0QVOM8dVQkHQCw
{{json}}

{
    "content":"文章内容"
}

###
POST {{url}}/updatePass
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlMTQyZjdkMTFiODAzMjA2NDM3OWU0NSIsImlhdCI6MTU3ODM4MTE5MX0.J85NuPlEqHK9dJ2UwgbjN4Me7ZjJP0QVOM8dVQkHQCw
{{json}}

{
    "password":"123456"
}

###
get {{url}}/getArticle
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlMTQyZjdkMTFiODAzMjA2NDM3OWU0NSIsImlhdCI6MTU3ODM4MTE5MX0.J85NuPlEqHK9dJ2UwgbjN4Me7ZjJP0QVOM8dVQkHQCw

###
get {{url}}/file
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlMTQyZjdkMTFiODAzMjA2NDM3OWU0NSIsImlhdCI6MTU3ODM4MTE5MX0.J85NuPlEqHK9dJ2UwgbjN4Me7ZjJP0QVOM8dVQkHQCw

### 
get {{url}}/getUser
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlMTQyZjdkMTFiODAzMjA2NDM3OWU0NSIsImlhdCI6MTU3ODM4MTE5MX0.J85NuPlEqHK9dJ2UwgbjN4Me7ZjJP0QVOM8dVQkHQCw